language: python
python:
- "3.3"
- "3.4"
- "3.5"
- nightly
matrix:
  allow_failures:
  - python: nightly
install:
- pip install --upgrade pip
- pip install appdirs
- pip install requests
- pip install --verbose lxml
- pip install pyflakes
cache:
  directories:
  - $HOME/.cache
script:
- nosetests -v
- export PAGER=cat
- python ./dbts show 123456 654321
- python ./dbts list adequate
- ./private/run-pyflakes

# vim:ts=2 sts=2 sw=2 et
