dist: trusty
sudo: false
language: python
python:
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
matrix:
  allow_failures:
  - python: "3.7-dev"
install:
- pip install --upgrade pip
- pip install --verbose lxml
- pip install pyflakes
- pip install docutils
cache: pip
script:
- nosetests -v
- export PAGER=cat
- python dbts show 123456 654321
- python dbts ls adequate
- private/run-pyflakes
- private/check-rst

# vim:ts=2 sts=2 sw=2 et
