#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2015-2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

from lib import cli

0_0  # Python >= 3.6 is required

if __name__ == '__main__':
    cli.main()

# vim:ts=4 sts=4 sw=4 et
