name: CI
on:
- push
- pull_request
jobs:
  main:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
        - python: '3.6'
          os: ubuntu-18.04
          lxml: lxml-3.8.0
        - python: '3.7'
          os: ubuntu-20.04
        - python: '3.8'
          os: ubuntu-20.04
        - python: '3.9'
          os: ubuntu-20.04
        - python: '3.10'
          os: ubuntu-22.04
        - python: '3.11'
          os: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: set up Python ${{matrix.python}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python}}
    - name: set up pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip-${{matrix.os}}-python${{matrix.python}}
    - name: install wheel
      run:
        python3 -m pip install wheel
    - name: install lxml
      env:
        lxml: ${{matrix.lxml || 'lxml'}}
      run: |
        python3 -m pip install ${lxml/-/==}
    - name: run unit tests
      run: |
        # work-around for <https://github.com/nose-devs/nose/issues/1115>:
        pip install 'setuptools<58'
        # work-around for <https://github.com/nose-devs/nose/issues/1099>:
        python3 -m pip install --no-binary ':all:' nose
        # work-around for <https://github.com/nose-devs/nose/issues/1116>:
        sed -i -e 's/ from unittest import _TextTestResult$/ from unittest import TextTestResult as _TextTestResult/' ${{env.pythonLocation}}/lib/python*/site-packages/nose/result.py
        python3 -m nose -v
    - name: run online tests
      run: |
        ./dbts show 123456 654321
        ./dbts ls adequate
      env:
        PAGER: cat
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra -v .
    - name: run pyflakes
      run: |
        python3 -m pip install pyflakes
        python3 -m pyflakes .
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
